version: '3.1'

services:

  pubsub:
    image: redis
    container_name: some-redis
    restart: always
    ports: 
      - "6379:6379"
    networks:
      - app-compose-network

  auth:
    image: quay.io/keycloak/keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: 
      - start-dev
      - --import-realm
    volumes:
      - ./MySGCApp-realm.json:/opt/keycloak/data/import/MySGCApp-realm.json  
    networks:
      - app-compose-network
  
  SGCApp:
    build: 
      context: .
      dockerfile: Dockerfile
    image: sgc_app
    container_name: 'sgc'
    restart: always
    volumes:
      - database:/app/Aplicacao/db
      - ./Aplicacao/db:/app/Aplicacao/db
    ports:
      - 7006:443
      - 5006:80
    networks:
      - app-compose-network
    depends_on:
      - pubsub
      - auth
      
networks:
  app-compose-network:
    driver: bridge
volumes:
  database: