version: '3.1'

services:
  auth:
    image: quay.io/keycloak/keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: 
      - start --auto-build
      - --db=dev-mem 
      - --hostname=localhost:8080 
      - --http-enabled=true
      - --hostname-strict-https=false
      - --import-realm
    volumes:
      - ./import/myrealm.json:/opt/keycloak/data/import/myrealm.json